# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'MyMortgage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 3.0'
  pod 'Charts', '~> 3.0'
  pod 'NVActivityIndicatorView', '~> 3.2'
  
  # Pods for MyMortgage

  target 'MyMortgageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyMortgageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
